# Enable streams
enable_infra1: true
enable_infra2: true
enable_depth: false
enable_color: false
enable_accel: true
enable_gyro: true
enable_sync: false
# IMU fuse method: 2 = linear interpolation (recommended)
unite_imu_method: 2
depth_module.emitter_enabled: 0
depth_module.infra1_profile: 848x480x30
depth_module.infra2_profile: 848x480x30
gyro_fps: 200
accel_fps: 200
